[tool.briefcase]
project_name = "seizure-tracker"
bundle = "com.hacknc22"
version = "0.0.1"
url = "https://hacknc22.com/seizure-tracker"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@hacknc22.com"

[tool.briefcase.app.seizure-tracker]
formal_name = "seizure-tracker"
description = "My first application"
icon = "src/seizure_tracker/resources/seizure-tracker"
sources = ['src/seizure_tracker']
requires = [
]


[tool.briefcase.app.seizure-tracker.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.seizure-tracker.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.seizure-tracker.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.seizure-tracker.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.seizure-tracker.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.seizure-tracker.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.seizure-tracker.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.seizure-tracker.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
